version: '3.8'

services:
  frontend:
    build: ./front
    container_name: temposwim-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./back
    container_name: temposwim-backend
    restart: unless-stopped
    volumes:
      - ./back:/var/www
      - ./back/storage:/var/www/storage
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: temposwim-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: temposwim
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: temposwim-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./docker/nginx:/etc/nginx/conf.d
    - ./back:/var/www
    - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local