services:
  laravel-docker:
    container_name: laravel-docker
    build: ./back
    ports:
      - 8000:80
    volumes:
      - /data/storage:/var/www/app/storage
    depends_on:
      - mysql_db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  react-docker:
    container_name: react-docker
    build: ./front
    ports:
      - 8080:80

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql