name: nsv1

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Docker
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Sleep for 10 seconds
        run: sleep 10s

      # Laravel DB migrate & seed supprimés ici

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install
        working-directory: back
