name: Deploy Application

on:
  push:
    branches: [ main ]  # ou master, selon votre branche principale
    paths:
      - 'front/**'
      - 'back/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Test Frontend
      run: |
        cd front
        npm install
        npm test
        
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json, pgsql
        
    - name: Test Backend
      run: |
        cd back
        composer install
        vendor/bin/phpunit
        
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: 168.231.107.219
        username: deployer
        key: ${{ secrets.SSH_PRIVATE_KEY }}
<<<<<<< Updated upstream
        script: /var/www/deploy/deploy.sh
=======
        script: /var/www/deploy/deploy.sh
>>>>>>> Stashed changes
