name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./front
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/frontend:latest
        
    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./back
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/backend:latest
        
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/deploy
          git pull
          docker compose pull
          docker compose up -d